InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Controllers/QuoteController.cs
using DAL.Entities;
using DAL.Managers;
using InsuranceAgencyQuotingSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace InsuranceAgencyQuotingSystem.Controllers
{
    public class QuoteController : Controller
    {
        #region Properties
        private DataManager _ctx = DataManager.Instance;
        private string _edAPIKey = "ntw94a7mf626pqsdbznxjupd";
        private string _Secret = "hVJ7y9AJuMuGJqpwpMgDuSBB";
        private string _edmoundurl = "https://api.edmunds.com/api/";
        #endregion

        #region Page Actions
        // GET: Quote
        public ActionResult Index()
        {
            return View();
        }

        // GET: Quote/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Quote/Create
        public ActionResult CreateCustomer()
        {
            // TODO: Add insert logic here
            var createQuoteModel = new CreateQuoteModel();

            // testAgentData 
            createQuoteModel.Agent.FirstName = "Keith";
            createQuoteModel.Agent.LastName = "Drummond";
            createQuoteModel.Agent.EmailAddress = "Agent1@InsuranceAgency.com";
            createQuoteModel.Agent.AgentId = 1;
            createQuoteModel.Agent.PhoneNumber = "5618460337";
            createQuoteModel.Agent.CreatedDate = DateTime.Now.AddDays(-14);
            createQuoteModel.Agent.LastModifiedDate = DateTime.Now;

            return View(createQuoteModel);
        }

        // POST: Quote/Create
        [HttpPost]
        public ActionResult CreateCustomer(Applicant applicant)
        {
            try
            {
                var createQuoteModel = new CreateQuoteModel();

                createQuoteModel.Applicant = applicant; 

                createQuoteModel.Applicant.ApplicantId = _ctx.Applicants.AddApplicant(applicant);
                createQuoteModel.Quote.ApplicantPageValid = true;
                createQuoteModel.Quote.ApplicantId = createQuoteModel.Applicant.ApplicantId;
                createQuoteModel.Quote.QuoteId = _ctx.Quotes.AddQuote(createQuoteModel.Quote);

                TempData["createQuoteModel"] = createQuoteModel;
                return RedirectToAction("CreatePolicy");
            }
            catch
            {
                return View(); 
                
            }
        }

        public ActionResult CreatePolicy()
        {
            var createQuoteModel = (CreateQuoteModel)TempData["createQuoteModel"];
            return View(createQuoteModel);
        }

        [HttpPost]
        public ActionResult CreatePolicy(Quote quote)
        {
            try
                {
                var createQuoteModel = new CreateQuoteModel();
                createQuoteModel.Applicant = _ctx.Applicants.GetApplicantById(quote.ApplicantId);
                quote.AgentId = -1;
                quote.ApplicantPageValid = true;
                quote.ApplicantQuoteInfoPageValid = true;

                createQuoteModel.Quote = quote;
                _ctx.Quotes.Update(quote);

                TempData["createQuoteModel"] = createQuoteModel;
                return RedirectToAction("CreateVehicles", createQuoteModel);
                }
                catch (Exception ex)
                {
                    return View();
                    throw;
                }
            
        }

        public ActionResult CreateDrivers()
        {
            var createQuoteModel = new CreateQuoteModel(); // (CreateQuoteModel)TempData["createQuoteModel"];
            createQuoteModel.Drivers = _ctx.Drivers.GetAllDrivers(); 
            return View(createQuoteModel); 
        }

        [HttpPost]
        public ActionResult CreateDrivers(string submitform, Driver driver)
        {
            if(ModelState.IsValid)
            {
                _ctx.Drivers.AddDriver(driver);
            }

            var createQuoteModel = new CreateQuoteModel(); 
            if (submitform == "Add")
            {
                //go back to vehicle page      
                createQuoteModel.Drivers.Add(driver);          
                return RedirectToAction("CreateDrivers", createQuoteModel);
            }
            else
            {
                createQuoteModel.Drivers.Add(driver);
                return RedirectToAction("CreateCoverage", createQuoteModel);
            }
         }

        public ActionResult VehicleDriverLink()
        {
            var createQuoteModel = new CreateQuoteModel();
            createQuoteModel.Drivers = _ctx.Drivers.GetAllDrivers();

            createQuoteModel.Vehicles = _ctx.Vehicles.GetAllVehicles(); 
             
            return View(createQuoteModel);
        }

        [HttpPost]
        public ActionResult VehicleDriverLink(FormCollection collection)
        {
            var createQuoteModel = new CreateQuoteModel(); 
            foreach(var key in collection)
            {
                var test = key;

                if(key.ToString().Contains("driver"))
                {
                    var Id = collection[key.ToString()].Split('_')[0];
                    var driverId = Convert.ToInt32(Id);
                    var vehicleId = Convert.ToInt32(key.ToString().Split('_')[1]);

                    if (vehicleId > 0 && driverId > 0)
                    {
                        var vehicle = _ctx.Vehicles.GetVehicleById(vehicleId);
                        vehicle.DriverId = driverId;
                        _ctx.Vehicles.Update(vehicle);
                    }

                }
                
            }
            return RedirectToAction("AddIncidents", createQuoteModel);
        }

        public ActionResult AddIncidents()
        {

            var createQuoteModel = new CreateQuoteModel();
            createQuoteModel.Drivers = _ctx.Drivers.GetAllDrivers();

            createQuoteModel.Vehicles = _ctx.Vehicles.GetAllVehicles();

            return View(createQuoteModel);
        }

        [HttpPost]
        public ActionResult AddIncidents(Incident incident)
        {
            
            return null; 
        }

        public ActionResult CreateVehicles()
        {
            var createQuoteModel = new CreateQuoteModel();  //(CreateQuoteModel)TempData["createQuoteModel"];
            createQuoteModel.Applicant = _ctx.Applicants.GetApplicantById(49);
            createQuoteModel.Quote = _ctx.Quotes.GetQuoteById(10);
            createQuoteModel.Vehicles = _ctx.Vehicles.GetAllVehicles(); 
            return View(createQuoteModel);
        }

        [HttpPost]
        public ActionResult CreateVehicles(string submitform, FormCollection collection)
        {
            var createQuoteModel = new CreateQuoteModel();
            
            #region buildVehicle
            var applicantId = Convert.ToInt32(collection["Quote.ApplicantId"]);
            var quoteId = Convert.ToInt32(collection["Quote.QuoteId"]);
            var applicant = _ctx.Applicants.GetApplicantById(applicantId);
            var quote = _ctx.Quotes.GetQuoteById(10);
            var newVehicle = new Vehicle(); 
            createQuoteModel.Applicant = applicant;

            newVehicle.Year = collection["Vehicle.Year"];
            newVehicle.Make = collection["Vehicle.Make"];
            newVehicle.Model = collection["Vehicle.Model"];
            newVehicle.Detail = collection["Vehicle.Detail"];
            newVehicle.CostNew = Convert.ToDouble(collection["Vehicle.CostNew"]);
            newVehicle.DriveTrainWheels = collection["Vehicle.DriveTrainWheels"];
            newVehicle.YearsOwnedLeased = Convert.ToInt32(collection["Vehicle.YearsOwnedLeased"]);
            newVehicle.GaragedElseWhere = Convert.ToBoolean(collection["Vehicle.GaragedElseWhere"]);

            

           // if (newVehicle.GaragedElseWhere)
            //{
                //get garaging address
                //newVehicle.GaragingAddress1 = collection["Vehicle.GaragedElseWhere"];
                //newVehicle.GaragingAddress2 = collection["Vehicle.GaragedElseWhere"];
                //newVehicle.GaragingCity = collection["Vehicle.GaragedElseWhere"];
                //newVehicle.GaragingState = collection["Vehicle.GaragedElseWhere"];
                //newVehicle.GaragingZipCode = collection["Vehicle.GaragedElseWhere"];
            //}
            //else
            //{
                newVehicle.GaragingAddress1 = quote.AddressLine1;
                newVehicle.GaragingAddress2 = quote.AddressLine2;
                newVehicle.GaragingCity = quote.City;
                newVehicle.GaragingState = quote.State;
                newVehicle.GaragingZipCode = quote.ZipCode;
            //}

            newVehicle.MilesToWorkSchool = collection["Vehicle.MilesToWorkSchool"];
            newVehicle.AnnualMileage = collection["Vehicle.AnnualMileage"];
            newVehicle.FarmUse = Convert.ToBoolean(collection["Vehicle.FarmUse"]);

            Titled titled;
            Enum.TryParse(collection["Vehicle.Titled"], out titled);

            VehicleUsuage usage;
            Enum.TryParse(collection["Vehicle.usage"], out usage);

            newVehicle.Titled = titled;
            newVehicle.Usage = usage;

            _ctx.Vehicles.AddVehicle(newVehicle);

            var quoteVehicles = _ctx.Vehicles.GetAllVehicles();
            createQuoteModel.Vehicles.Add(newVehicle);
            #endregion  

            if (submitform == "Add")
            {
                //go back to vehicle page                
                return RedirectToAction("CreateVehicles", createQuoteModel);
            }
            else
            {
                return RedirectToAction("CreateDrivers", createQuoteModel);
            }
        }

        public ActionResult CreateCoverage(CreateQuoteModel createQuoteModel)
        {
            return View(createQuoteModel);
        }

        [HttpPost]

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/AddIncidents.cshtml
@model  InsuranceAgencyQuotingSystem.Models.CreateQuoteModel

@{
    ViewBag.Title = "AddIncidents";
}

<h2>Add Incidents</h2>

@using (Html.BeginForm("AddIncidents", "Quote", FormMethod.Post, new { @class = "form-horizontal", @id = "myform" }))
{
    <center>
        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th>
                        Incident Type
                    </th>
                    <th>
                        Incident Cost
                    </th>
                    <th>
                        Time Frame
                    </th>
                    <th>
                        Driver Involved
                    </th>
                    <th>
                        At Fault
                    </th>
                </tr>
                <tr>
                    <td>
                        <select class="form-control" data-val="true"
                                data-val-required="The Type field is required."
                                id="Type" name="Type">
                            <option value="-1">Select a Driver</option>
                            <option value="1">Claim</option>
                            <option value="2">Incident</option>
                        </select>
                        <div class="text-danger field-validation-error" data-valmsg-for="type"
                             data-valmsg-replace="true">Please select a Type.</div>
                    </td>
                    <td>
                        <select class="form-control" data-val="true"
                                data-val-required="The Cost field is required."
                                id="Cost" name="Cost">
                            <option value="-1">Select a Cost</option>
                            <option value="1"><= $250</option>
                            <option value="2"><= $500</option>
                            <option value="3"><= $1000</option>
                            <option value="4">> $1000</option>
                        </select>
                        <div class="text-danger field-validation-error" data-valmsg-for="cost"
                             data-valmsg-replace="true">Please select a Cost.</div>
                    </td>
                    <td>
                        <select class="form-control" data-val="true"
                                data-val-required="The Time Frame field is required."
                                id="TimeFrame" name="TimeFrame">
                            <option value="-1">Select a Time period</option>
                            <option value="1">< a year ago</option>
                            <option value="2">< 2 years ago</option>
                            <option value="3">< 3 years ago</option>
                            <option value="4">> 3 years ago</option>
                        </select>
                        <div class="text-danger field-validation-error" data-valmsg-for="time"
                             data-valmsg-replace="true">Please select a incident time period.</div>
                    </td>
                    <td>
                        <select class="form-control" data-val="true"
                                data-val-required="The Model field is required."
                                id="DriverId" name="DriverId">
                            <option value="-1">Select a Driver</option>
                            @foreach (var driver in Model.Drivers)
                            {
                                var fullName = driver.FirstName + " " + driver.LastName;
                            <option value=@driver.DriverId>@fullName</option>

                            }
                        </select>
                        <div class="text-danger field-validation-error" data-valmsg-for="driver"
                             data-valmsg-replace="true">Please select a driver.</div>
                    </td>
                    <td>
                        <div class="col-md-3 nopadding">
                             <div class="radio-inline">
                                @Html.RadioButton("AtFault", "true") Yes
                            
                                @Html.RadioButton("AtFault", "false") No
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div class="row">
            <br>
            <input type="button" id="cancel" class="btn btn-info" value="Back">
            <input type="submit" name="submitform" class="btn btn-info" value="Add">
            <input type="submit" name="submitform" class="btn btn-info" value="Next">

        </div>

    </center>
}

<br />
<center>
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>
                    Incident Type
                </th>
                <th>
                    Incident Cost
                </th>
                <th>
                    @Html.DisplayName("Commands")
                </th>
            </tr>

            @foreach (var item in Model.Incidents)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>


                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>
                        <button id="editIncident" value="Edit">Edit</button>
                        <button id="deleteIncident" value="Delete">Delete</button>
                    </td>
                </tr>
            }

        </table>


    </div>
</center>

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/BuyPolicy.cshtml
@{
    ViewBag.Title = "BuyPolicy";
}

<h2>BuyPolicy</h2>

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/CreateCoverages.cshtml
@{
    ViewBag.Title = "CreateCoverages";
}

<h2>CreateCoverages</h2>

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/CreateCustomer.cshtml
@model  InsuranceAgencyQuotingSystem.Models.CreateQuoteModel

@{
    ViewBag.Title = "Create";
}


@section Sidebar {
    <p> This sidebar has "Create Quote Page" specific content</p>
    <center>
        <table>
            <tr>
                <th>
                    Status
                </th>
                <th>
                    Page
                </th>
            </tr>

            <tr>
                <td>
                    @if (Model.Quote.ApplicantPageValid)
                    {
                    <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Applicant Information Page</a>
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Quote.ApplicantQuoteInfoPageValid)
                    {
                        <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Policy Information Page</a>
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Quote.DriverPageValid)
                    {
                    <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Driver Page</a>
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Quote.VehiclePageValid)
                    {
                    <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Vehicle Page</a>
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Quote.CoveragePageValid)
                    {
                    <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Coverage Page</a>
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Quote.RatePageValid)
                    {
                    <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Rate Page</a>
                </td>
            </tr>
            <tr>
                <td>
                    @if (Model.Quote.BuyPolicyPageValid)
                    {
                    <span class="glyphicon glyphicon-check" style="color:green"></span>
                    }
                    else
                    {
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:red"></span>
                    }
                </td>
                <td>
                    <a href="#">Buy Policy Page</a>
                </td>
            </tr>
        </table>
    </center>

}


<center>
    <div class="has-error form-group">
        <!-- 'has-error' class has been added on parent form-group div -->
        @using (Html.BeginForm("CreateCustomer", "Quote", FormMethod.Post, new { @class = "form-horizontal", @id = "myform" }))
        {
            <h2>Customer Information</h2>

            <div class="row nopadding">

                <div class="col-md-4 nopadding">
                    <label for="FirstName">First name</label>
                    @Html.TextBoxFor(m => m.Applicant.FirstName, null, new { @class="form-control", data_val_required ="The First name field is required.", type="text"})
                 <div class="text-danger field-validation-error" data-valmsg-for= "Applicant.FirstName"
                         data-valmsg-replace="true">The First name field is required.</div>
                </div>

                <div class="col-md-2 nopadding">
                    <label for="Mi">Middle Initial</label>
                    @Html.TextBoxFor(m => m.Applicant.MI, null, new { @class = "form-control"})                    
                </div>

                <div class="col-md-4 nopadding">
                    <label for="LastName">Last name</label>
                    @Html.TextBoxFor(m => m.Applicant.LastName, null, new { @class = "form-control", data_val_required = "The Last name Field is required." })
                    <div class="text-danger field-validation-error" data-valmsg-for="Applicant.LastName"
                         data-valmsg-replace="true">The Last name field is required.</div>
                </div>

            </div>

            <center>
                <div class="row nopadding">
                    <div class="col-md-2 nopadding">
                        <label for="HomePhone">Home Phone </label>
                        @Html.TextBoxFor(m => m.Applicant.PhoneNumber, null, new { @class = "form-control", data_val_required = "The Phone Number Field is required." })
                        <div class="text-danger field-validation-error" data-valmsg-for="Applicant.PhoneNumber"
                             data-valmsg-replace="true">The Home Phone field is required.</div>
                    </div>

                    <div class="col-md-2 nopadding">
                        <label for="CellPhone">Cell Phone Number</label>
                        @Html.TextBoxFor(m => m.Applicant.CellNumber, null, new { @class = "form-control" })

                    </div>

                    <div class="col-md-4">
                        <label for="EmailAddress">Email Address</label>
                        @Html.TextBoxFor(m => m.Applicant.EmailAddress, null, new { @class = "form-control", data_val_required = "The Email Address Field is required." })
                        <div class="text-danger field-validation-error" data-valmsg-for="Applicant.EmailAddress"
                             data-valmsg-replace="true">The Email Address field is required.</div>
                    </div>

                    <div class="col-md-2 nopadding">
                        <label for="Date of Birth">Date of Birth </label>
                        @Html.TextBoxFor(m => m.Applicant.DOB, null, new { @class = "form-control", data_val_required = "The Date of Birth field is required.", type = "date" })
                       <div class="text-danger field-validation-error" data-valmsg-for="Applicant.DOB"
                             data-valmsg-replace="true">The Date of Birth field is required.</div>
                    </div>

                </div>

                <div class="row">
                    <br>
                    <input type="button" id="cancel" class="btn btn-info" value="Cancel">
                    <input type="submit" id="submit" class="btn btn-info" value="Next  Button">

                </div>
            </center>
        }
    </div>
</center>

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Create A New Quote", "CreateCustomer", "Quote", null, new { @class = "btn btn-primary btn-large" })

<div id="quoteAgentRoot"></div>
<br />
<br />

<div id="quoteVehicleRoot"></div>

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/Rate.cshtml
@{
    ViewBag.Title = "Rate";
}

<h2>Rate</h2>

InsuranceAgencyQuotingSystem/InsuranceAgencyQuotingSystem/Views/Quote/VehicleDriverLink.cshtml
@model InsuranceAgencyQuotingSystem.Models.CreateQuoteModel


@{
    ViewBag.Title = "VehicleDriverLink";
}

<h2>Select Primary Drivers for Vehicles</h2>

@using (Html.BeginForm("VehicleDriverLink", "Quote", FormMethod.Post, new { @class = "form-horizontal", @id = "myform" }))
{

    <center>
        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th>
                       <label>Vehicle</label>
                    </th>
                    <th>
                       <label>Driver</label>
                    </th>
                                      
                </tr>

                @foreach (var item in Model.Vehicles)
                {
                    var ddId = "driver_" + item.VehicleId;
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Year)
                            @Html.DisplayFor(modelItem => item.Make)
                            @Html.DisplayFor(modelItem => item.Model)
                        </td>
                        <td>
                            <select class="form-control" data-val="true"
                                    data-val-required="The Model field is required."
                                    id=@ddId name=@ddId>
                                <option value="-1">Select a Driver</option>
                                @foreach (var driver in Model.Drivers)
                                {
                                    var fullName = driver.FirstName + " " + driver.LastName;
                                    <option value=@driver.DriverId>@fullName</option>
                                 
                                }
                            </select>
                            <div class="text-danger field-validation-error" data-valmsg-for=@ddId
                                 data-valmsg-replace="true">Please select a driver.</div>
                        </td>

                    </tr>
                }

            </table>
        </div>
        <div class="row">
            <br>
            <input type="button" id="cancel" class="btn btn-info" value="Back">
            <input type="submit" name="submitform" class="btn btn-info" value="Next">

        </div>
    </center>
}